# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.2

    working_directory: ~/repo

    steps:
      - add_ssh_keys
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile" }}

      # run tests!
      - run:
          name: run tests
          command: bundle exec rake

      # collect reports
      - store_test_results:
          path: ~/repo/test-results
      - store_artifacts:
          path: ~/repo/test-results
          destination: test-results

  publish:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.2

    working_directory: ~/repo

    steps:
      - add_ssh_keys
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile" }}

      - run:
          name: run tests
          command: bundle exec rake

      - run:
          name: publish
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            mkdir ~/.gem
            cat .circleci/gem_credentials | sed -e "s/__RUBYGEMS_API_KEY__/${RUBYGEMS_API_KEY}/" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
            bundle exec fastlane publish
            shred -u ~/.gem/credentials


workflows:
  version: 2

  tests:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - 'master'

  deploy:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - 'master'
